# Generated by Django 5.2.12 on 2026-04-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_project_image_project_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image — it will be saved to ImageKit automatically.', null=True, upload_to='temp_uploads/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
